category: add-ons
date: "2024-08-28T09:31:00"
title: Data Driven Trial Spawner Configurations
description: since Java got data driven trial spawner configurations and Bedrock has not.
source: https://x.com/slicedlime/status/1828787407346368596
